# Site settings
title:       Wagner Souza
email:       wagnersza@gmail.com
author:      Wagner Souza
description: "Um pouco sobre Infra Estrutura Web"
url: /
# Google analytics
google_analytics:

# Optional features
animated:           true
show_related_posts: true
show_post_footers:  true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: wagnersza

# Social icons
show_social_icons: true
github_username: wagnersza
# stackoverflow_id:
twitter_username: wagnersza
# google_plus_id:
linkedin_username: wagnersza
# angellist_username:
# bitcoin_url:
# paypal_url:
# flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: 'Compartilhe esse post!'
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
# share_googleplus: true
share_linkedin: true
# share_digg: true
share_tumblr: true
# share_reddit: true
# share_stumbleupon: true
# share_hackernews: true

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     3
sass:
  compressed: true
